language: php

matrix:
  fast_finish: true

  include:
    - os: linux
      php: '5.6'

    - os: linux
      php: '7.0'

    - os: linux
      php: 'nightly'

    - os: linux
      php: 'hhvm'

    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - _OSX=10.11
        - _PHP: php56

    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - _OSX=10.11
        - _PHP: php70

    - os: osx
      osx_image: xcode7.1
      language: generic
      env:
        - _OSX=10.10
        - _PHP: php56

    - os: osx
      osx_image: xcode7.1
      language: generic
      env:
        - _OSX=10.10
        - _PHP: php70

    - os: osx
      osx_image: beta-xcode6.2
      language: generic
      env:
        - _OSX=10.9
        - _PHP: php56

    - os: osx
      osx_image: beta-xcode6.2
      language: generic
      env:
        - _OSX=10.9
        - _PHP: php70

  allow_failures:
    - php: hhvm

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" && "${TRAVIS_PHP_VERSION}" == 7* ]]; then COLLECT_COVERAGE=true ; fi
  - if [[ "${COLLECT_COVERAGE}" != "true" ]]; then phpenv config-rm xdebug.ini || true ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then /usr/bin/env bash build/prepare_osx_env.sh ; fi

install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then /usr/bin/env bash build/handle_brew_pkg.sh "${_PHP}" ; fi
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

before_script:
  - /usr/bin/env bash build/custom_php_ini.sh
  - mkdir -p build/logs

script:
  - php vendor/bin/phpunit --configuration phpunit.xml

after_script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then travis_retry php vendor/bin/coveralls -v ; fi
